### ISSUE TITLE
`npm run dev`: npm ERR! Failed at the cov-x@ dev script 'cross-env NODE_ENV=development supervisor -w server,app.js app'.

### ISSUE THREAD

**Issue by MikeChongCan** [hilongjw/vue-ssr-hmr-template#2]
``` bash
npm run dev

> cov-x@ dev /Users/wildcat/WebstormProjects/ohmyqrcode
> cross-env NODE_ENV=development supervisor -w server,app.js app

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn supervisor ENOENT
    at exports._errnoException (util.js:1012:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:577:11)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/wildcat/.nvm/versions/node/v6.3.1/bin/node" "/Users/wildcat/.nvm/versions/node/v6.3.1/bin/npm" "run" "dev"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! cov-x@ dev: `cross-env NODE_ENV=development supervisor -w server,app.js app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cov-x@ dev script 'cross-env NODE_ENV=development supervisor -w server,app.js app'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cov-x package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development supervisor -w server,app.js app
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cov-x
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cov-x
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/wildcat/WebstormProjects/ohmyqrcode/npm-debug.log
```

**Comment by hilongjw** [comment]
```
sudo npm run dev
```

**Comment by Morganjackson** [comment]
@hilongjw I'm seeing the same error and `sudo npm run dev` doesnt work.

**Comment by hilongjw** [comment]
@Morganjackson  Are you install supervisor with `npm install supervisor -g`, and make sure supervisor is work fine.

**Comment by Morganjackson** [comment]
@hilongjw Perfect! `npm install supervisor -g` fixed it.
