### ISSUE TITLE
this._init  is not a function

### ISSUE THREAD

**Issue by sudeepdk** [hilongjw/vue-ssr-hmr-template#6]
ERROR in ./client/index/views/Tag.vue
Module build failed: TypeError: this._init is not a function
    at Object.Vue$2 (/home/sudeep/sudeep_dk/dk/vuejs/vue-ssr-hmr-template/node_modules/vue/dist/vue.runtime.common.js:3407:8)
 @ ./client/index/router/index.js 8:10-37
 @ ./client/index/app.js
 @ ./client/index/client-entry.js
 @ multi index

ERROR in ./client/index/views/Login.vue
Module build failed: TypeError: this._init is not a function
    at Object.Vue$2 (/home/sudeep/sudeep_dk/dk/vuejs/vue-ssr-hmr-template/node_modules/vue/dist/vue.runtime.common.js:3407:8)
 @ ./client/index/router/index.js 9:12-41
 @ ./client/index/app.js
 @ ./client/index/client-entry.js
 @ multi index

**Comment by sudeepdk** [comment]
Need to add   "file- **loader**' 
Need to add vue-**loader**
module: {
        loaders: [{
            test: /\.vue$/,
            loader: 'vue-loader'
        }, {
            test: /\.js$/,
            loader: 'babel-loader',
            exclude: /node_modules/
        }, {
            test: /\.(png|jpg|gif|svg|ttf|woff|eot)$/,
            loader: 'file-loader',
            query: {
                name: 'file/[name].[ext]'
            }
        }]
    },
