### ISSUE TITLE
node app.js 打开浏览器 localhost:8080报错

### ISSUE THREAD

**Issue by yutiansut** [hilongjw/vue-ssr-hmr-template#7]
node --debug-brk=11455 --nolazy app.js 
Debugger listening on 127.0.0.1:11455
App (production) is now running on PORT 8080!
[Vue warn]: Error when rendering root instance: 
ReferenceError: _h is not defined
    at Proxy.render (__vue_ssr_bundle__:828:10)
    at Vue$2.Vue._render (D:\projects\collections\vueexample\vue-ssr-hmr-template\node_modules\.2.1.10@vue\dist\vue.runtime.common.js:2216:22)
    at render (D:\projects\collections\vueexample\vue-ssr-hmr-template\node_modules\.2.1.10@vue-server-renderer\build.js:6252:26)
    at RenderStream.ref.renderToStream [as render] (D:\projects\collections\vueexample\vue-ssr-hmr-template\node_modules\.2.1.10@vue-server-renderer\build.js:6287:9)
    at RenderStream.tryRender (D:\projects\collections\vueexample\vue-ssr-hmr-template\node_modules\.2.1.10@vue-server-renderer\build.js:96:12)
    at RenderStream._read (D:\projects\collections\vueexample\vue-ssr-hmr-template\node_modules\.2.1.10@vue-server-renderer\build.js:125:12)
    at RenderStream.Readable.read (_stream_readable.js:348:10)
    at resume_ (_stream_readable.js:737:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[Vue warn]: Error when rendering root instance: 
ReferenceError: _h is not defined
    at Proxy.render (__vue_ssr_bundle__:828:10)
    at Vue$2.Vue._render (D:\projects\collections\vueexample\vue-ssr-hmr-template\node_modules\.2.1.10@vue\dist\vue.runtime.common.js:2216:22)

**Comment by hilongjw** [comment]
@yutiansut  vue-template-compiler@2.1.5 renamed _h to _c, 
vuejs/vue#4536

 Related to [vuejs/vue@4b51ad0](https://github.com/vuejs/vue/commit/4b51ad048306367a6fb6fbee7445e086d855f31e)

**Comment by yutiansut** [comment]
this._h to this.$createElement 
我看到一个解决办法是这样?

**Comment by hilongjw** [comment]
@yutiansu vue and vue-template-compiler are both upgraded to 2.1.5 or later

**Comment by yutiansut** [comment]
#vue 是2.8版本
PS C:\Users\yutia> vue -V
2.8.0
#vue-template-compiler我不知道怎么查版本号
我先修改了package.json里的要求
```
  "dependencies": {
    "express": "^4.14.0",
    "pug": "^2.0.0-beta6",
    "serialize-javascript": "^1.3.0",
    "vue": "^2.0.1",
    "vue-router": "^2.0.0",
    "vue-server-renderer": "^2.0.1",
    "vue-ssr": "^0.2.2",
    "vue-template-compiler": "^2.1.5",
    "vuex": "^2.0.0-rc.3",
    "vuex-router-sync": "^3.0.0"
  },
```
再npm i
这样行吗

**Comment by hilongjw** [comment]
可以的

**Comment by yutiansut** [comment]
还是在大量报错 cmd页面全是滚滚的错误我都来不及复制....
基本都是类似这个,似乎还是_h的问题
```
[Vue warn]: Error when rendering root instance:
ReferenceError: _h is not defined
    at Proxy.render (__vue_ssr_bundle__:828:10)
    at Vue$2.Vue._render (D:\projects\collections\vueexample\vue-ssr-hmr-template\node_modules\.2.1.10@vue\dist\vue.runtime.common.js:2216:22)
    at render (D:\projects\collections\vueexample\vue-ssr-hmr-template\node_modules\.2.1.10@vue-server-renderer\build.js:6252:26)
    at RenderStream.render (D:\projects\collections\vueexample\vue-ssr-hmr-template\node_modules\.2.1.10@vue-server-renderer\build.js:6287:9)
    at RenderStream.tryRender (D:\projects\collections\vueexample\vue-ssr-hmr-template\node_modules\.2.1.10@vue-server-renderer\build.js:96:12)
    at RenderStream._read (D:\projects\collections\vueexample\vue-ssr-hmr-template\node_modules\.2.1.10@vue-server-renderer\build.js:125:12)
    at RenderStream.Readable.read (_stream_readable.js:348:10)
    at resume_ (_stream_readable.js:737:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[Vue warn]: Error when rendering root instance:
ReferenceError: _h is not defined
    at Proxy.render (__vue_ssr_bundle__:828:10)
    at Vue$2.Vue._render (D:\projects\collections\vueexample\vue-ssr-hmr-template\node_modules\.2.1.10@vue\dist\vue.runtime.common.js:2216:22)
    at render (D:\projects\collections\vueexample\vue-ssr-hmr-template\node_modules\.2.1.10@vue-server-renderer\build.js:6252:26)
    at RenderStream.render (D:\projects\collections\vueexample\vue-ssr-hmr-template\node_modules\.2.1.10@vue-server-renderer\build.js:6287:9)
    at RenderStream.tryRender (D:\projects\collections\vueexample\vue-ssr-hmr-template\node_modules\.2.1.10@vue-server-renderer\build.js:96:12)
    at RenderStream._read (D:\projects\collections\vueexample\vue-ssr-hmr-template\node_modules\.2.1.10@vue-server-renderer\build.js:125:12)
    at RenderStream.Readable.read (_stream_readable.js:348:10)
    at resume_ (_stream_readable.js:737:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by yutiansut** [comment]
所以是我需要降级版本号是吗?

**Comment by hilongjw** [comment]
```bash
npm i vue@2.1.8 --save
npm i vue-template-compiler@2.1.8 --save
```

**Comment by yutiansut** [comment]
执行以后出来这个结果
```
PS D:\projects\collections\vueexample\vue-ssr-hmr-template> npm i vue@2.1.8 --sace-dev
npm WARN update-linked node_modules\vue needs updating to 2.1.8 from 2.1.10 but we can't, as it's a symlink
npm WARN cov-x@ No repository field.
npm WARN cov-x@ No license field.
PS D:\projects\collections\vueexample\vue-ssr-hmr-template> npm i vue-template-compiler@2.1.8 --sace-dev
npm WARN update-linked node_modules\vue-template-compiler needs updating to 2.1.8 from 2.1.10 but we can't, as it's a symlink
npm WARN cov-x@ No repository field.
npm WARN cov-x@ No license field.
```

**Comment by hilongjw** [comment]
```bash
npm i vue@2.1.10 --save
npm i vue-template-compiler@2.1.10 --save
```

**Comment by yutiansut** [comment]
降级不成功诶
```
PS D:\projects\collections\vueexample\vue-ssr-hmr-template> npm i vue@2.1.8 --save
npm WARN update-linked node_modules\vue needs updating to 2.1.8 from 2.1.10 but we can't, as it's a symlink
npm WARN cov-x@ No repository field.
npm WARN cov-x@ No license field.
PS D:\projects\collections\vueexample\vue-ssr-hmr-template> npm i vue-template-compiler@2.1.8 --save
npm WARN update-linked node_modules\vue-template-compiler needs updating to 2.1.8 from 2.1.10 but we can't, as it's a symlink
npm WARN cov-x@ No repository field.
npm WARN cov-x@ No license field.
```

**Comment by hilongjw** [comment]
这里安装不了指定版本的问题应该是npm 的bug, 你是window？ [https://github.com/npm/npm/issues/10013](https://github.com/npm/npm/issues/10013)

**Comment by yutiansut** [comment]
windows 10 预览版 build 15014
